# Generated by Django 3.2.6 on 2021-10-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='pins/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('makeup', 'makeup'), ('art', 'art'), ('henna', 'henna'), ('nature', 'nature'), ('recipes', 'recipes'), ('friendship', 'friendship'), ('beauty_products', 'beauty_products'), ('flowers', 'flowers'), ('hairstyles', 'hairstyles'), ('babies', 'babies'), ('child', 'child'), ('sketching', 'sketching'), ('travel', 'travel'), ('yoga', 'yoga'), ('nails', 'nails'), ('birthday', 'birthday'), ('disney', 'disney'), ('dress', 'dress'), ('birds', 'birds'), ('jewellery', 'jewellery'), ('positive_quotes', 'positive_quotes'), ('drawing', 'drawing'), ('love', 'love'), ('shoes', 'shoes'), ('morning', 'morning')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user1',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_clone.images')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_clone.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_clone.images')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_clone.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('makeup', 'makeup'), ('art', 'art'), ('henna', 'henna'), ('nature', 'nature'), ('recipes', 'recipes'), ('friendship', 'friendship'), ('beauty_products', 'beauty_products'), ('flowers', 'flowers'), ('hairstyles', 'hairstyles'), ('babies', 'babies'), ('child', 'child'), ('sketching', 'sketching'), ('travel', 'travel'), ('yoga', 'yoga'), ('nails', 'nails'), ('birthday', 'birthday'), ('disney', 'disney'), ('dress', 'dress'), ('birds', 'birds'), ('jewellery', 'jewellery'), ('positive_quotes', 'positive_quotes'), ('drawing', 'drawing'), ('love', 'love'), ('shoes', 'shoes'), ('morning', 'morning')], max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_clone.user1')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_clone.user1'),
        ),
    ]
