# Generated by Django 3.2.6 on 2021-10-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interest',
            table='Interest',
        ),
        migrations.AlterModelTable(
            name='user1',
            table='user1',
        ),
    ]
