# Generated by Django 3.2.6 on 2021-10-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_clone', '0002_auto_20211030_1714'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user1',
            table=None,
        ),
    ]
