# Generated by Django 3.2.6 on 2021-10-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_clone', '0003_auto_20211030_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
