# Generated by Django 3.2.6 on 2021-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_clone', '0004_auto_20211031_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='dob',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('makeup', 'makeup'), ('art', 'art'), ('henna', 'henna'), ('nature', 'nature'), ('recipes', 'recipes'), ('friendship', 'friendship'), ('beauty_products', 'beauty_products'), ('flowers', 'flowers'), ('hairstyles', 'hairstyles'), ('babies', 'babies'), ('child', 'child'), ('sketching', 'sketching'), ('travel', 'travel'), ('yoga', 'yoga'), ('nails', 'nails'), ('birthday', 'birthday'), ('disney', 'disney'), ('dress', 'dress'), ('birds', 'birds'), ('jewellery', 'jewellery'), ('positive_quotes', 'positive_quotes'), ('drawing', 'drawing'), ('love', 'love'), ('shoes', 'shoes'), ('morning', 'morning'), ('other', 'other')], max_length=20),
        ),
    ]
