# Generated by Django 3.2.6 on 2021-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_clone', '0005_auto_20211110_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='dob',
            field=models.DateTimeField(default=1984),
        ),
    ]
