# Generated by Django 3.2.6 on 2021-11-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_clone', '0012_alter_user1_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='dob',
        ),
    ]
